 UPDATE admin_controller SET fieldcaption='Served By'  WHERE  fieldname='employee_name' 
; UPDATE admin_controller SET fieldcaption='Client Name'  WHERE  fieldname='client_name' 
; UPDATE admin_controller SET fieldcaption='Agent Name'  WHERE  fieldname='agent_name' 
; UPDATE admin_controller SET fieldcaption='Bank Name'  WHERE  fieldname='bank_name' 
; UPDATE admin_controller SET fieldcaption='Unit'  WHERE  fieldname='unit_name' 
; UPDATE admin_controller SET fieldcaption='Attachment'  WHERE  fieldname='attachments_name' 
; UPDATE admin_controller SET fieldcaption='Branch Name'  WHERE  fieldname='branch_name' 
; UPDATE admin_controller SET fieldcaption='Company Name'  WHERE  fieldname='company_name' 
; UPDATE admin_controller SET fieldcaption='Event'  WHERE  fieldname='event_name' 
; UPDATE admin_controller SET fieldcaption='Reminder'  WHERE  fieldname='reminder_name' 
; UPDATE admin_controller SET fieldcaption='Landlord Name'  WHERE  fieldname='landlord_name' 
; UPDATE admin_controller SET fieldcaption='Next of Kin'  WHERE  fieldname='nextofkin_name' 
; UPDATE admin_controller SET fieldcaption='Property Name'  WHERE  fieldname='property_name' 
; UPDATE admin_controller SET fieldcaption='Tenant Name'  WHERE  fieldname='tenant_name' 
; UPDATE admin_controller SET fieldcaption='Underwriter'  WHERE  fieldname='insurer_name' 
; UPDATE admin_controller SET fieldcaption='Policy Number'  WHERE  fieldname='policy_name' 
; UPDATE admin_controller SET fieldcaption='Policy Type'  WHERE  fieldname='policytype_name' 
; UPDATE admin_controller SET fieldcaption='Product'  WHERE  fieldname='product_name' 
; UPDATE admin_controller SET fieldcaption='Product'  WHERE  fieldname='risk _name' 